### PR TITLE
Add openni2_tracker_nodelet

### PR DESCRIPTION
**Pull request by iory**
make openni2_tracker nodelet.

### CODE REVIEW

**Comment by k-okada** [comment]
running `catkin b` causes following error, what should I do?
```
_______________________________________________________________________________
Errors     << openni2_tracker:cmake /home/k-okada/catkin_ws/ws_openni/logs/openni2_tracker/build.cmake.000.log
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Nite2_INCLUDEDIR
```

**Comment by iory** [comment]
in bash
```
export NITE2_INCLUDE=/usr/include/nite2
```

**Comment by iory** [comment]
I installed nite2 by following instruction.
https://github.com/ros-drivers/openni2_tracker/issues/4#issuecomment-221925076

**Comment by k-okada** [comment]
not working,,,
```
k-okada@p40-yoga:~/catkin_ws/ws_openni/src/openni2_tracker/launch$ roslaunch openni2_tracker_nodelet.launch 
... logging to /home/k-okada/.ros/log/d526c604-c5c2-11e6-bd2e-0050b6d94125/roslaunch-p40-yoga-29395.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

WARN: unrecognized 'param' tag in <include> tag
started roslaunch server http://p40-yoga:40194/

SUMMARY
========

PARAMETERS
 * /camera/camera_nodelet_manager/num_worker_threads: 4
 * /camera/depth_rectify_depth/interpolation: 0
 * /camera/driver/auto_exposure: True
 * /camera/driver/auto_white_balance: True
 * /camera/driver/color_depth_synchronization: False
 * /camera/driver/depth_camera_info_url: 
 * /camera/driver/depth_frame_id: camera_depth_opti...
 * /camera/driver/depth_registration: False
 * /camera/driver/device_id: #1
 * /camera/driver/rgb_camera_info_url: 
 * /camera/driver/rgb_frame_id: camera_rgb_optica...
 * /openni2_tracker_nodelet/camera_frame_id: camera_link
 * /rosdistro: indigo
 * /rosversion: 1.11.20

NODES
  /camera/
    camera_nodelet_manager (nodelet/nodelet)
    depth_metric (nodelet/nodelet)
    depth_metric_rect (nodelet/nodelet)
    depth_points (nodelet/nodelet)
    depth_rectify_depth (nodelet/nodelet)
    depth_registered_sw_metric_rect (nodelet/nodelet)
    driver (nodelet/nodelet)
    points_xyzrgb_sw_registered (nodelet/nodelet)
    register_depth_rgb (nodelet/nodelet)
    rgb_rectify_color (nodelet/nodelet)
  /
    camera_base_link (tf/static_transform_publisher)
    camera_base_link1 (tf/static_transform_publisher)
    camera_base_link2 (tf/static_transform_publisher)
    camera_base_link3 (tf/static_transform_publisher)
    openni2_tracker_nodelet (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[camera/camera_nodelet_manager-1]: started with pid [29413]
process[camera/driver-2]: started with pid [29414]
process[camera/rgb_rectify_color-3]: started with pid [29415]
process[camera/depth_rectify_depth-4]: started with pid [29417]
process[camera/depth_metric_rect-5]: started with pid [29425]
process[camera/depth_metric-6]: started with pid [29432]
process[camera/depth_points-7]: started with pid [29450]
process[camera/register_depth_rgb-8]: started with pid [29453]
process[camera/points_xyzrgb_sw_registered-9]: started with pid [29457]
process[camera/depth_registered_sw_metric_rect-10]: started with pid [29461]
process[camera_base_link-11]: started with pid [29468]
process[camera_base_link1-12]: started with pid [29471]
process[camera_base_link2-13]: started with pid [29478]
process[camera_base_link3-14]: started with pid [29483]
process[openni2_tracker_nodelet-15]: started with pid [29498]
[ INFO] [1482139029.946381421]: Loading nodelet /openni2_tracker_nodelet of type openni2_tracker/OpenNI2TrackerNodelet to manager camera/camera_nodelet_manager with the following remappings:
[ INFO] [1482139029.965101445]: waitForService: Service [/camera/camera_nodelet_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1482139030.949775844]: Initializing nodelet with 4 worker threads.
[ INFO] [1482139030.961511615]: waitForService: Service [/camera/camera_nodelet_manager/load_nodelet] is now available.
[ INFO] [1482139031.243208960]: device_id: #1
Warning: USB events thread - failed to set priority. This might cause loss of data...
[ INFO] [1482139034.104166496]: Device "1d27/0609@1/13" found.
[ WARN] [1482139034.238354368]: Reconfigure callback failed with exception void openni2_wrapper::OpenNI2Device::setDepthVideoMode(const openni2_wrapper::OpenNI2VideoMode&) @ /tmp/binarydeb/ros-indigo-openni2-camera-0.2.7/src/openni2_device.cpp @ 519 : Couldn't set depth video mode: 
	This stream is open by other components. Configuration cannot be changed.
```
also we need to copy `s.dat`, I think this has been fixed sometimes ago....

```
[ INFO] [1482135067.136976652]: Loading nodelet /openni2_tracker_nodelet of type openni2_tracker/OpenNI2TrackerNodelet to manager camera/camera_nodelet_manager with the following remappings:
[ INFO] [1482135067.139124677]: waitForService: Service [/camera/camera_nodelet_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1482135067.161051772]: Initializing nodelet with 4 worker threads.
[ INFO] [1482135067.186316660]: waitForService: Service [/camera/camera_nodelet_manager/load_nodelet] is now available.
[ INFO] [1482135067.599182498]: device_id: #1
Warning: USB events thread - failed to set priority. This might cause loss of data...
Could not find data file ./NiTE2/s.dat
current working directory = /home/k-okada/.ros
[FATAL] [1482135069.416860260]: Couldn't create user tracker
```

**Comment by iory** [comment]
I tested same environment.
I found that timing of nodelet's initialization makes this error.
```
roslaunch openni2_launch openni2.launch
```
after abobe command,
```
 rosrun nodelet nodelet load openni2_tracker/OpenNI2TrackerNodelet /camera/camera_nodelet_manager
```
This is succeeded.
But I have no idea to launch these nodelets simulaneously.

**Comment by iory** [comment]
Rewrite code and wait depth_image for initialization of device(xtion) in openni2_tracker.

**Comment by k-okada** [comment]
thanks you , moved to https://github.com/ros-drivers/openni2_tracker/pull/8

**Pull request merged**
